# spring配置
spring:
  # 配置mysql数据源
  datasource:
    # 连接引擎位置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url
    url: jdbc:mysql://localhost:3306/blog_new?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # 用户名
    username: blog
    # 密码
    password: 123456

  # 配置邮箱
  mail:
    host: smtp.163.com
    username: synergism2022@163.com
    password: FXDKZJSNILSAHUVX

  # 配置redis
#  redis:
#    # ip地址
#    host: localhost
#    # 端口
#    port: 6379
#    # 用户名
#    username: root
#    # 密码
#    password:
#    # 最大连接数
#    jedis:
#      pool:
#        max-active: 8

# 服务配置
server:
  # 端口号
  port: 8088
